### ISSUE TITLE
Matching numbers

### ISSUE THREAD

**Issue by jhoopes** [moodleou/moodle-qtype_pmatch#26]
Hi Tim,

I found one more bug, and it's how the code matches 0.  

In the pmatch_matcher_number class in the match word function, you normalize the number and then check for a tolerance.  If the word to match is 0, the tolerance can't validate as 0 < 0 will always be false.  so changing it to 0 <= 0 fixes the problem.

**Comment by timhunt** [comment]
This was fixed long ago by commit da98e06a6bf3bd535fbbeeec0bf50e70b8c5cd8f. Closing.
