### ISSUE TITLE
Minor typo in an English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodleou/moodle-qtype_pmatch#28]
Hi, 
While I was translating the qtype_pmatch plugin language strings in AMOS I saw a tiny typo in  the ie_nofullstop string:

Full stop characters are not allowed in pmatch expressions. (Decimal points in the middle of nubmers are OK.)

'nubmers' should be 'numbers' (I think).

Thanks in advance for your help.

**Comment by timhunt** [comment]
Thanks for reporting this. I have fixed it, but I am not going to release a whole new version to the Moodle plugins DB for this, so the change will not show up for most people until we do a release for some other reason.
