### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by ewallah** [moodleou/moodle-qtype_pmatch#29]
When I follow "Edit" # question/type/pmatch/tests/behat/testquestion_backup.feature:41 Moodle exception: Exception - Notice: Only variables should be passed by reference in [dirroot]/question/type/pmatch/edit_pmatch_form.php on line 180

Error code: generalexceptionmessage

Stack trace:
line 158 of /lib/behat/lib.php: Exception thrown
line 180 of /question/type/pmatch/edit_pmatch_form.php: call to behat_error_handler()
line 104 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_answer_accuracy_fields()
line 70 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 202 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 201 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 57 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 193 of /question/question.php: call to question_type->create_editing_form()

Same error:
And I click on "Edit" "link" in the "My first pattern match question" "table_row" # question/type/pmatch/tests/behat/testquestion_edit.feature:51
And I click on "Edit" "link" in the "My first pattern match question" "table_row" # question/type/pmatch/tests/behat/try_rule.feature:42

Moodle 3.1
PHP 7.0.8

**Comment by timhunt** [comment]
I guess you are the first version to try this question type with PHP7, and it seems there are some things that need to be fixed up. Sorry, I cannot say exactly when we will get time to do that. Pull requests welcome, if anyone gets there before we do. Thanks.

**Comment by timhunt** [comment]
This problem no longer occurs. Closing.
