### ISSUE TITLE
Upgrading from V1.9 to V2.0

### ISSUE THREAD

**Issue by dirkcgrunwald** [moodleou/moodle-qtype_pmatch#30]
I have a question about upgrading v1.9 -> v2.0 - I'm trying to upgrade a prior installation which has version 2015101200 with tag v1.9 to tag v2.0 which has version 2016080400 but requires version 2015111600. After looking at the different version tags, I don't see a database upgrade path from 2015101200 to 2015111600. What's the intended upgrade path?

**Comment by timhunt** [comment]
What do you mean, you don't see an upgrade path? Just try the upgrade on a test server. I am sure you will find it works.

**Comment by dirkcgrunwald** [comment]
That's what caused me to discover the issue.

![screenshot from 2016-12-06 07-46-22](https://cloud.githubusercontent.com/assets/989516/20929702/27a90a58-bb88-11e6-997c-55bc5ab291b3.png)

**Comment by timhunt** [comment]
When pmatch v2.0 says it requires Moodle version 2015111600, that means it needs Moodle 3.0. They errror message in yoru screen-grab makes no sense. The two version numbers are the same,a nd neither is 2016080400.

**Comment by dirkcgrunwald** [comment]
The upgrade is being done as part of a Docker build. I'm attaching the new Dockerfile and the git clone lines from the previous version. That one used Moodle v3.1.1 and this one steps to v3.2  for Moodle. 

The dockerfile attached builds a "base" image to which I can add apache or nginx and then extend by other dockerfiles with e.g. out Shibboleth layers for test & deployment systems, so it's not a completely deployable setup.

That's the only upgrade steps I took -- I'll go check the DB information after a thesis proposal this AM.

```
 RUN	cd /tmp && \
-	git clone --recursive --single-branch -b v3.1.1 \
+	git clone --recursive --single-branch -b v3.2.0 \
 	    --single-branch git://git.moodle.org/moodle.git && \
 ....
 	\
-	git clone --recursive --single-branch -b v1.9 \
+	git clone --recursive --single-branch -b v2.0 \
 	    https://github.com/moodleou/moodle-qtype_pmatch \
 	    /var/www/html/question/type/pmatch && \

**Comment by timhunt** [comment]
I must admit that I have not tested this question type with Moodle 3.2 yet (it's on my todo list!). I would expect it to just work.

**Comment by dirkcgrunwald** [comment]
The error arises because line 67 in `question/type/pmatch/db/update.php` is:

```
        upgrade_plugin_savepoint(true, 2015101200, 'qtype', 'pmatch');

and line 345 of `lib/upgradelib.php` is:

```
    if ($dbversion >= $version) {

There's a reasonable argument that this `>=` should be a `>` -- another solution would be to pass in 2015101200-1 for the same purpose, but I'm not familiar enough with the upgrade logic to know if this is locally meaningful but globally stupid.

However, either solution (i.e. forcing the test to not throw an exception) did allow the upgrade to continue & it appears to function.

**Comment by timhunt** [comment]
I think this won't be a problem any more we more recent versions of pmatch. Closing this. Comment if I am wrong.
