### ISSUE TITLE
Tiny typo in one English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodleou/moodle-qtype_pmatch#31]
Hi,

While I was translating in AMOS the English language strings for  minresponses | qtype_pmatch ,  I think I spotted one tiny typo:

'Minumum number of responses' should be 'Minimum number of responses' (I think).

Thanks in advance for your help.

**Comment by timhunt** [comment]
Thanks for detecting and reporting this bug Germán. It will be fixed in the next version.
