### ISSUE TITLE
Testing table does not return full information about which rules match

### ISSUE THREAD

**Issue by sangwinc** [moodleou/moodle-qtype_pmatch#34]
I'm using the testing table to generate my rules (test-driven question authoring).

However, if the testing table "Showing the responses for the selected question:" the "Rules" column is blank if the computed mark is "zero".  This makes it very difficult to see which rules are operating, and gives the misleading suggestion the match is falling all the way to the end.

Is this a design decision?

**Comment by timhunt** [comment]
This sounds like a bug to me. Thanks for reporting it.

**Comment by timhunt** [comment]
We have now fixed this. The information about which rules match what should be much clearer in the next version, which should be released soon.
