### ISSUE TITLE
Latest pmatch (2018111900) blocks running of unit tests elsewhere!

### ISSUE THREAD

**Issue by sangwinc** [moodleou/moodle-qtype_pmatch#36]
Really sorry, but I get this error when running "vendor/bin/phpunit --group qtype_stack".  This is blocking running any unit tests of STACK!

```
csangwin@faraday:/var/www/html/demo$ vendor/bin/phpunit --group qtype_stack
Moodle 3.4.1 (Build: 20180115)
Php: 7.0.32.1.8.1, mariadb: 10.0.37, OS: Linux 3.16.0-4-amd64 x86_64
PHP Fatal error:  Class 'core_privacy\tests\provider_testcase' not found in /var/www/html/demo/question/type/pmatch/tests/privacy_provider_test.php on line 31

Fatal error: Class 'core_privacy\tests\provider_testcase' not found in /var/www/html/demo/question/type/pmatch/tests/privacy_provider_test.php on line 31
```

[My solution is to comment out class privacy_provider_test extends .... from line 31 of pmatch/tests/privacy_provider_test.php, but that doesn't fix the problem.  Sorry to leave this hanging, but it is 18:30 on a Friday and I want to run my unit tests overnight!

**Comment by timhunt** [comment]
Is there a reason you are running with Moodle 3.4.**1**?

Upgrading Moodle core to latest 3.4.x should fix this.

**Comment by sangwinc** [comment]
Lethargy on a dev moodle machine?!

**Comment by timhunt** [comment]
I am going to close this as won't fix. The world has moved on past Moodle 3.4.x.
