### ISSUE TITLE
Translation. Can this be translated?

### ISSUE THREAD

**Issue by dinism** [moodleou/moodle-qtype_pmatch#40]
When creating a question:
![imagem](https://user-images.githubusercontent.com/14828021/61160961-9ed3bf80-a4f9-11e9-9bc2-2c9f4844b24c.png)
Thanks
I'm PT-PT translator

**Comment by germanvaleroelizondo** [comment]
These English language strings are inside the edit_pmatch_form.php file.

If you edit them (e.g. with Notepad ++) locally you can get a working translation locally.

**Comment by timhunt** [comment]
Duplicate of #46. Closing this one.
