### ISSUE TITLE
Installed on 3.4.6 site which has now crashed.

### ISSUE THREAD

**Issue by elektrosmart** [moodleou/moodle-qtype_pmatch#43]
I installed this plugin on my Moodle 3.4.6 site and it has now crashed. I got several error messages when I went to update the database. Now I just get a white screen at ….../admin/index.php.
The error starts off:
Exception - syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE). 
There is several more lines of error but I can't seem to get the image to upload to this post.

How can I uninstall this to get my site up and running again? Please help.

**Comment by timhunt** [comment]
Did the error message give a file name and a line number? That is kind-of crucial information.

**Comment by elektrosmart** [comment]
Hi Tim,
Yes I’ll send you the image with this email.
Regards

**Comment by elektrosmart** [comment]
Hi again,

Thank you so much for replying so quickly. I am in real trouble if I cant get this working. It’s already 2:30am here.

After installing the latest version of the plugin 37 and getting the error, to try and fix it, I renamed the folder:

question/type/pmatch to pmatch_old.

Then I copied the prior version 35 to the folder:

question/type/pmatch

I was hoping going back a version might solve the problem, but no.

Then I got this error:

[cid:image001.png@01D548DA.7AA71BA0]
And, now a white screen and the install goes automatically to http://www.elektrosmart.com.au/elektrolearn/admin/index.php
I have about 200 students using the site and many will be in at 8:00am tomorrow.

Regards

Jaimie

**Comment by timhunt** [comment]
Attachment did not come through. Anyway, image is not very helpful. Just copy and paste the full text of the email.

If you just copy the old code over the new code, that won't remove any newly added files. You need to delete folder before copying the old folder in.

Probably the error here is because you are using an old version of PHP, and the code has started to use PHP7 constructs.

**Comment by elektrosmart** [comment]
Sorry Tim,
I tweaked the config.ini file and am able to get the following message instead of the blank white page.


Fatal error: Cannot redeclare qtype_pmatch_pluginfile() (previously declared in /home/jaimiecarey/public_html/elektrolearn/question/type/pmatch_35/lib.php:34) in /home/jaimiecarey/public_html/elektrolearn/question/type/pmatch_37/lib.php on line 47

The site is using PHP 7.0

[cid:image001.png@01D548DD.A6A4AD00]


The first image that did not go through is as follows…
[cid:image002.png@01D548DD.A6A4AD00]
So you recommend I:
1: delete 37 folder
2: Rename 35 folder back to correct name
3:Update PHP to 7.1 7.2 or 7.3 which are all available.

Regards

Jaimie

**Comment by timhunt** [comment]
You should not have folders called pmatch_37 or pmatch_35 in question/type

(Certainly sensible to keep backup copies of thost files, but keep them outside the Moodle codebase.)

**Comment by elektrosmart** [comment]
Ok – thanks a lot.

I deleted the pmatch_35 folder. Renamed the pmatch_37 folder to pmatch.

The site is kind of working again, I’m getting errors like the following when I go into a quiz.
[cid:image001.png@01D548E3.289DE470]

I’ll delete the pmatch folder and see what happens after that.

**Comment by elektrosmart** [comment]
Problem solved. Deleted pmatch folder. I'll attack this again when I get some time after I upgrade to PHP 7.3
