### ISSUE TITLE
Install on Moodle 3.6 fails with PHP 7.0

### ISSUE THREAD

**Issue by TarjanPeter** [moodleou/moodle-qtype_pmatch#44]
I'm trying to add this on a fresh install of Moodle 3.6 on Debian. I'm getting the following errors. 

![Fullscreen capture 2019 09 04  163031](https://user-images.githubusercontent.com/7457234/64264613-e0994900-cf31-11e9-9813-da873ce009c6.jpg)

**Comment by timhunt** [comment]
What version of PHP are you using?

**Comment by TarjanPeter** [comment]
7.0

**Comment by timhunt** [comment]
Drat! public const is a PHP 7.1 thing, and I had forgotten that Moodle 3.6 is supposed to support PHP 7.0.

If you need a quick fix, then can you edit these three lines (https://github.com/moodleou/moodle-qtype_pmatch/blob/master/classes/local/spell/qtype_pmatch_spell_checker.php#L47) to delete teh word public?

Or, can you upgrade to a newer version of PHP?

**Comment by TarjanPeter** [comment]
Well, the install at least worked with the quick fix.
On the other hand, when I go to "Manage Question Types", all I get is: 
Exception - syntax error, unexpected '?'
Removing pmatch gets rid of the error too.

Upgrading php is unfortunately not an option.

**Comment by timhunt** [comment]
Fixed in the latest version.
