### ISSUE TITLE
Improvement: please replace language string constants with variables

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodleou/moodle-qtype_pmatch#46]
Hi,

This improved version is great, but it would be even greater if you replaced the English language constants in the file 'edit_pmatch_form.php' with string variables declared in /lang/ed/qtype_pmatch.php .And they would be available for all AMOS translators.

Thanks in advance

**Comment by timhunt** [comment]
Doh! sorry. Don't know how that got through code review.

**Comment by germanvaleroelizondo** [comment]
No worries mate !

**Comment by germanvaleroelizondo** [comment]
By the way, there seem to be some very nice examples somewhere here; they would be even nicer if those English language strings were also string variables available in AMOS.

**Comment by timhunt** [comment]
This should be fixed in the latest version.

**Comment by germanvaleroelizondo** [comment]
Thanks.
