### ISSUE TITLE
Box\Spout\Reader\Common\Creator\ReaderEntityFactory not found

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-qtype_pmatch#51]
pmatch: latest master
Moodle: 3.7.7

12) qtype_pmatch_testquestion_testcase::test_currentquestion
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:69
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_testcase" question/type/pmatch/tests/testquestion_testcase.php

13) qtype_pmatch_testquestion_amati_rule_suggestion::test_find_pmatch_equivalents_to_amati_commands
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/amati_rule_suggestion_test.php:1184
/path/to/moodle/question/type/pmatch/tests/amati_rule_suggestion_test.php:155
/path/to/moodle/question/type/pmatch/tests/amati_rule_suggestion_test.php:72
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_amati_rule_suggestion" question/type/pmatch/tests/amati_rule_suggestion_test.php

14) qtype_pmatch_testquestion_amati_rule_suggestion::test_currentquestion
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:69
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_amati_rule_suggestion" question/type/pmatch/tests/amati_rule_suggestion_test.php

15) qtype_pmatch_testquestion_responses_test::test_add_responses
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:161
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

16) qtype_pmatch_testquestion_responses_test::test_update_response
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:201
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

17) qtype_pmatch_testquestion_responses_test::test_delete_responses_by_ids
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:225
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

18) qtype_pmatch_testquestion_responses_test::test_get_question_grade_summary_counts
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:244
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

19) qtype_pmatch_testquestion_responses_test::test_grade_response
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:287
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

20) qtype_pmatch_testquestion_responses_test::test_load_responses_from_file
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:329
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

21) qtype_pmatch_testquestion_responses_test::test_try_rule
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:373
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

22) qtype_pmatch_testquestion_responses_test::test_grade_rule_with_responses
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:441
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

23) qtype_pmatch_testquestion_responses_test::test_get_rule_accuracy_counts
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:473
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

24) qtype_pmatch_testquestion_responses_test::test_regrading
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:513
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

25) qtype_pmatch_testquestion_responses_test::test_save_rule_matches
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:579
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

26) qtype_pmatch_testquestion_responses_test::test_validate_csv_file_type
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:760
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

27) qtype_pmatch_testquestion_responses_test::test_validate_xlsx_file_type
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:266
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:69
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:802
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

28) qtype_pmatch_testquestion_responses_test::test_validate_ods_file_type
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:284
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:72
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:844
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

29) qtype_pmatch_testquestion_responses_test::test_get_responses with data set #2 ('/data/apache/htdocs/moodlesit...al.csv', 4, array(array(0, 'Response 1'), array(1, 'Response 2'), array(0, 'Response 3'), array(1, 'Response 4')))
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:890
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

30) qtype_pmatch_testquestion_responses_test::test_get_responses with data set #3 ('/data/apache/htdocs/moodlesit...l.xlsx', 4, array(array(0, 'Response 1'), array(1, 'Response 2'), array(0, 'Response 3'), array(1, 'Response 4')))
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:266
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:69
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:890
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

31) qtype_pmatch_testquestion_responses_test::test_get_responses with data set #4 ('/data/apache/htdocs/moodlesit...al.ods', 4, array(array(0, 'Response 1'), array(1, 'Response 2'), array(0, 'Response 3'), array(1, 'Response 4')))
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:284
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:72
/path/to/moodle/question/type/pmatch/tests/testquestion_responses_test.php:890
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

32) qtype_pmatch_testquestion_responses_test::test_currentquestion
Error: Class 'Box\Spout\Reader\Common\Creator\ReaderEntityFactory' not found

/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:248
/path/to/moodle/question/type/pmatch/classes/testquestion_import_helper.php:66
/path/to/moodle/question/type/pmatch/classes/testquestion_responses.php:737
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:84
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:111
/path/to/moodle/question/type/pmatch/tests/testquestion_testcase.php:69
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_pmatch_testquestion_responses_test" question/type/pmatch/tests/testquestion_responses_test.php

**Comment by Peterburnett** [comment]
I also have run into this issue on latest master on a 3.5.13+

**Comment by timhunt** [comment]
Right. If you look in version.php, you will see that the latest version of the plugin only works with Moodle 3.8. This because we had to make changes to this plugin to match the https://tracker.moodle.org/browse/MDL-65762 change in Moodle core. Oops! looks like I only updated the human-readable text, and missed this line: https://github.com/moodleou/moodle-qtype_pmatch/blob/master/version.php#L28. Sorry.

If you want to run something that is essentially latest master, but with older Moodle, I think you can do it if you just revert this one commit: https://github.com/moodleou/moodle-qtype_pmatch/commit/fb74876437b543a67032da30dcf9d9064994f5ed. (And hopefully if you konw enough to be runnign latest master version from git, you know how to do that.)

**Comment by timhunt** [comment]
Version.php fixed now, but be careful pulling, because if you have previous master in your old Moodle site, then it may just stop working.
