### ISSUE TITLE
Error: Return value of qtype...null returned

### ISSUE THREAD

**Issue by firstrincewind** [moodleou/moodle-qtype_pmatch#55]
Hello, i just updated moodle from 3.x (2018 version) to latest, and since then i have the error from qtype_pmatch plugin:

"Return value of qtype_pmatch\local\spell\qtype_pmatch_spell_checker::get_display_name_for_language_code() must be of the type string, null returned"

This appeared, when i f.e. use the searchbox in administrationarea, or install new plugins. I already de- and reinstall it, error stays, i have 2 languages, de and en, php is 7.2.26

- the update was not possible with copy new version over old, so i install fresh, switched to old db and reinstall all plugins with latest, everything runs fine exept that error mentioned above, someone a idea what could trigger that? It is under development here: http://moodle.timug.net

Thx

**Comment by timhunt** [comment]
Looking at the code https://github.com/moodleou/moodle-qtype_pmatch/blob/master/classes/local/spell/qtype_pmatch_spell_checker.php#L210 this could only happen if your server has a spell-check dictionay installed for a language which Moodle does not know the name of.

And, given how many lanuage names Moodle knows, that is quite surprising (https://github.com/moodle/moodle/blob/master/lang/en/iso6392.php#L31).

Can you work out which installed language is causing the problem? (And, we should patch the code to not give an error in this case.)

**Comment by timhunt** [comment]
I think https://github.com/moodleou/moodle-qtype_pmatch/commit/unknown-lang-fix is the required fix, but I have no way to test it. Can you try that?

**Comment by timhunt** [comment]
I have no idea why that link shows as 'unknow' but it is the right link.

**Comment by timhunt** [comment]
OK. Fix added. It can't hurt.
