### ISSUE TITLE
Main branch regression

### ISSUE THREAD

**Issue by Peterburnett** [moodleou/moodle-qtype_pmatch#56]
In swapping from master->main, some commits appear to have been dropped. 

Eg https://github.com/moodleou/moodle-qtype_pmatch/pull/54 This patch is no longer present on the main branch and unit tests again throw a deprecation notice on PHP 7.4

**Comment by Peterburnett** [comment]
Hi @timhunt, just a ping, this is causing a bunch of CI noise, and am trying to avoid swapping to a fork for production. Are you able to have a peek at this sometime?
Thanks

**Comment by timhunt** [comment]
Sorry for the delay. I have added that commit back (I think it was the only one lost). Is having it on main enough, or should I push a new release to the plugsin DB?
