### ISSUE TITLE
Failed behat tests

### ISSUE THREAD

**Issue by dragos5436** [moodleou/moodle-qtype_pmatch#59]
**Behat test - Test the try rule feature.Test the pmatch try rule feature**
/var/www/html/question/type/pmatch/tests/behat/try_rule.feature:35

And I choose "Edit question" action for "My first pattern match question" in the question bank: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test the try rule feature.Test the pmatch rules response feature**
/var/www/html/question/type/pmatch/tests/behat/try_rule.feature:78

When I add a "Pattern match" question filling the form with:: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test all the basic functionality of pmatch question type.Create, edit then preview a pattern match question.**
/var/www/html/question/type/pmatch/tests/behat/basic_test.feature:21

And I add a "Pattern match" question filling the form with:: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test backup and restore of a pmatch question with responses and matches.Test backup and restore with testquestion data.**
/var/www/html/question/type/pmatch/tests/behat/testquestion_backup.feature:20

And I choose "Edit question" action for "My first pattern match question" in the question bank: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Create new a response for a pattern match question.Create an existing test response for a pattern match question.**
/var/www/html/question/type/pmatch/tests/behat/testquestion_create_response.feature:23

And I press key "27" in the field "Correct": Key Down / Up events only make sense for modifier keys. (InvalidArgumentException)

**Behat test - Test answer accuracy and response coverage.Get standard responses graded against current answer rules.**
/var/www/html/question/type/pmatch/tests/behat/testquestion_edit.feature:29

When I choose "Edit question" action for "My first pattern match question" in the question bank: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test the model answer functionality of pmatch question type.Validation of the model answer**
/var/www/html/question/type/pmatch/tests/behat/modelanswer_test.feature:38

When I choose "Edit question" action for "Frog but not toad" in the question bank: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test the model answer functionality of pmatch question type.Validation of the model answer with non-standard options**
/var/www/html/question/type/pmatch/tests/behat/modelanswer_test.feature:59

When I choose "Edit question" action for "Spanish question" in the question bank: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test all the basic functionality of testquestion question type.Test edit response.**
/var/www/html/question/type/pmatch/tests/behat/testquestion_basic_test.feature:43

And I press key "13" in the field "Edit response": Key Down / Up events only make sense for modifier keys. (InvalidArgumentException)

**Behat test - Test spelling check of a pmatch question.Spell checking with Spell checking library is set to No spell checking available**
/var/www/html/question/type/pmatch/tests/behat/spellcheck_test.feature:19

When I choose "Edit question" action for "My first pattern match question" in the question bank: debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Behat test - Test the rule creation assistant.Using the rule creation assistant.**
/var/www/html/question/type/pmatch/tests/behat/rule_creation_assistant.feature:22

And I click on ".submitbutton" "css_element": debugging() message/s found:
String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 298 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 407 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->get_per_answer_fields()
line 89 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->add_per_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

String [grade,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7278 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 209 of /question/type/pmatch/edit_pmatch_form.php: call to get_string()
line 110 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_other_answer_fields()
line 73 of /question/type/pmatch/edit_pmatch_form.php: call to qtype_pmatch_edit_form->add_per_answer_fields()
line 217 of /question/type/edit_question_form.php: call to qtype_pmatch_edit_form->definition_inner()
line 214 of /lib/formslib.php: call to question_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 60 of /question/type/pmatch/edit_pmatch_form.php: call to question_edit_form->__construct()
line 217 of /question/type/questiontypebase.php: call to qtype_pmatch_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()
 (Exception)

**Comment by lucaboesch** [comment]
That is probably covered by MDL-71941

**Comment by dragos5436** [comment]
The tests are also failing in Moodle 4.0

**Comment by timhunt** [comment]
This has just been fixed. Closing.
